---
title: "Lihu'e Mobility"
knit: (function(inputFile, encoding) { 
      out_dir <- '../../docs';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'lihue-mobility.html')) })
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = FALSE)

library(sf)
library(tidyverse)
library(leaflet)
library(htmltools)
library(reshape2)
library(scales)
library(plotly)
library(kableExtra)
library(readr)
# source("scripts/docs/func.R")
```

## Parking Utilization Rate
```{r echo=FALSE, warning=FALSE, message=FALSE}
coord_global <- 4236

on_street_util <- read_rds("../../data/lihue-civiccentermobility/on_street.rds", refhook=NULL)
off_street_util <- read_rds("../../data/lihue-civiccentermobility/off_street.rds", refhook=NULL)

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  
  addPolylines(data = on_street_util %>% filter(sample_time == "util_school_wed_am"),
               weight = 2,
               color = ~case_when(utilization >= .01 & utilization < .3 ~"#bdd7e7",
                                     utilization >= .3 & utilization < .6 ~"#6baed6",
                                     utilization >= .6 & utilization < .75 ~"#2171b5",
                                     utilization >= .75 & utilization < .85 ~"#4ea652",
                                     utilization >= .85 & utilization < .95 ~"#ffcb05",
                                     utilization >= .95 ~"#d63f3e",
                                     TRUE ~"#cccccc"),
               opacity = 1,
               label = ~lapply(as.list(paste0(
                 "<div>",
                 "<table>",
                 "<tr>","<th colspan='4' style=\"background-color:#666666; color: #ffffff;\">",
                 lot_no, ": ", lot_name, 
                 "</th>","</tr>",
                 "<tr>","<td>Lot Owner: </td>","<td>",lot_owner,"</td>","</tr>",
                 "<tr>","<td>Total Spaces: </td>","<td>",total_spaces,"</td>","</tr>",
                 "</table>",
                 "</div>"
               )), HTML),
               group = "School Wednesday AM") %>% 
  addPolygons(data = off_street_util %>% filter(sample_time == "util_school_wed_am"),
              stroke = FALSE,
              fillColor = ~case_when(utilization >= .01 & utilization < .3 ~"#bdd7e7",
                                     utilization >= .3 & utilization < .6 ~"#6baed6",
                                     utilization >= .6 & utilization < .75 ~"#2171b5",
                                     utilization >= .75 & utilization < .85 ~"#4ea652",
                                     utilization >= .85 & utilization < .95 ~"#ffcb05",
                                     utilization >= .95 ~"#d63f3e",
                                     TRUE ~"#cccccc"),
              fillOpacity = 1,
              label = ~lapply(as.list(paste0(
                 "<div>",
                 "<table>",
                 "<tr>","<th colspan='4' style=\"background-color:#666666; color: #ffffff;\">",
                 lot_no, ": ", lot_name, 
                 "</th>","</tr>",
                 "<tr>","<td>Lot Owner: </td>","<td>",lot_owner,"</td>","</tr>",
                 "<tr>","<td>Total Spaces: </td>","<td>",total_spaces,"</td>","</tr>",
                 "</table>",
                 "</div>"
               )), HTML),
              group = "School Wednesday AM") %>% 
  
  addPolylines(data = on_street_util %>% filter(sample_time == "util_school_wed_pm"),
               weight = 2,
               color = ~case_when(utilization >= .01 & utilization < .3 ~"#bdd7e7",
                                     utilization >= .3 & utilization < .6 ~"#6baed6",
                                     utilization >= .6 & utilization < .75 ~"#2171b5",
                                     utilization >= .75 & utilization < .85 ~"#4ea652",
                                     utilization >= .85 & utilization < .95 ~"#ffcb05",
                                     utilization >= .95 ~"#d63f3e",
                                     TRUE ~"#cccccc"),
               opacity = 1,
               label = ~lapply(as.list(paste0(
                 "<div>",
                 "<table>",
                 "<tr>","<th colspan='4' style=\"background-color:#666666; color: #ffffff;\">",
                 lot_no, ": ", lot_name, 
                 "</th>","</tr>",
                 "<tr>","<td>Lot Owner: </td>","<td>",lot_owner,"</td>","</tr>",
                 "<tr>","<td>Total Spaces: </td>","<td>",total_spaces,"</td>","</tr>",
                 "</table>",
                 "</div>"
               )), HTML),
               group = "School Wednesday PM") %>% 
  addPolygons(data = off_street_util %>% filter(sample_time == "util_school_wed_pm"),
              stroke = FALSE,
              fillColor = ~case_when(utilization >= .01 & utilization < .3 ~"#bdd7e7",
                                     utilization >= .3 & utilization < .6 ~"#6baed6",
                                     utilization >= .6 & utilization < .75 ~"#2171b5",
                                     utilization >= .75 & utilization < .85 ~"#4ea652",
                                     utilization >= .85 & utilization < .95 ~"#ffcb05",
                                     utilization >= .95 ~"#d63f3e",
                                     TRUE ~"#cccccc"),
              fillOpacity = 1,
              label = ~lapply(as.list(paste0(
                 "<div>",
                 "<table>",
                 "<tr>","<th colspan='4' style=\"background-color:#666666; color: #ffffff;\">",
                 lot_no, ": ", lot_name, 
                 "</th>","</tr>",
                 "<tr>","<td>Lot Owner: </td>","<td>",lot_owner,"</td>","</tr>",
                 "<tr>","<td>Total Spaces: </td>","<td>",total_spaces,"</td>","</tr>",
                 "</table>",
                 "</div>"
               )), HTML),
              group = "School Wednesday PM") %>% 
  
  addLegend(position = "bottomleft",
            colors = c("#d63f3e", "#ffcb05", "#4ea652", "#2171b5", "#6baed6", "#bdd7e7", "#cccccc"),
            labels = c("> 95%", "86-95%", "76-85%", "61-75%", "31-60%", "< 30%", "NA"),
            title = "Parking Utilization Rate",
            opacity = 1) %>% 
  addLayersControl(
    baseGroups = c("School Wednesday AM",
                   "School Wednesday PM"),
    options = layersControlOptions(collapsed=FALSE)
  )
```


## Jobs to/from Lihu'e Civic Center (LEHD 2019)
- 714 people both live and work within the Civic Center block groups.
- Top 30 block groups for jobs coming into Civic Center block groups make up 3,941 out of 5,647 (69.8%) of all jobs.
- Top 30 block groups for jobs going out of the Civic Center block groups make up 1450 out of 2,335 (62.1%) of all jobs.
- Civic Center Block Groups: Tract 405 (Block Groups 2, 3, 4, 5)

```{r echo=FALSE, warning=FALSE, message=FALSE}
coord_global <- 4236
block_groups_lst <- c("150070405002", "150070405004",
                      "150070405005", "150070405003")

origin <- read_rds("../../data/lihue-civiccentermobility/lehd_analysis/lehd2019_jobs_from_lihue.rds")
destination <- read_rds("../../data/lihue-civiccentermobility/lehd_analysis/lehd2019_jobs_to_lihue.rds")
soi <- read_rds("../../data/lihue-civiccentermobility/lehd_analysis/walkshed_15min.rds")
block_groups <- read_rds("../../data/lihue-civiccentermobility/lehd_analysis/filtered_block_groups.rds") %>% 
  mutate(internal = if_else(GEOID %in% block_groups_lst, "TRUE", "FALSE"))

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  setView(lat = 21.977, lng = -159.366, zoom = 14) %>% 
  addMapPane("Block Groups", zIndex = 210) %>%
  addMapPane("Civic Center Block Groups", zIndex = 215) %>%
  addMapPane("Sphere of Influence", zIndex = 220) %>% 
  addMapPane("Work Locations of People Who Live Within Civic Center Block Groups", zIndex = 250) %>% 
  addMapPane("Home Locations of People Who Work Within Civic Center Block Groups", zIndex = 250) %>% 

  addPolygons(data = block_groups %>% filter(internal == "TRUE"),
              fillOpacity = 0,
              weight = 3, color = "black", opacity = 1,
              label = ~paste0("GEOID: ", GEOID),
              group = "Civic Center Block Groups") %>% 
  
  addPolylines(data = origin,
               weight = ~case_when(total_jobs > 0 & total_jobs <= 50 ~2,
                                   total_jobs > 50 & total_jobs <= 100 ~3,
                                   total_jobs > 100 & total_jobs <= 300 ~5,
                                   total_jobs > 300 & total_jobs <= 600 ~8,
                                   TRUE ~1),
               color = ~case_when(total_jobs > 0 & total_jobs <= 50 ~"#fee5d9",
                                  total_jobs > 50 & total_jobs <= 100 ~"#fcae91",
                                  total_jobs > 100 & total_jobs <= 300 ~"#fb6a4a",
                                  total_jobs > 300 & total_jobs <= 600 ~"#cb181d",
                                  TRUE ~"#cccccc"),
               opacity = 1,
               label = ~paste0("Total jobs: ",total_jobs),
               group = "Work Locations of People Who Live Within Civic Center Block Groups") %>% 
  addPolylines(data = destination,
               weight = ~case_when(total_jobs > 0 & total_jobs <= 50 ~2,
                                   total_jobs > 50 & total_jobs <= 100 ~3,
                                   total_jobs > 100 & total_jobs <= 300 ~5,
                                   total_jobs > 300 & total_jobs <= 600 ~8,
                                  TRUE ~1),
               color = ~case_when(total_jobs > 0 & total_jobs <= 50 ~"#fee5d9",
                                  total_jobs > 50 & total_jobs <= 100 ~"#fcae91",
                                  total_jobs > 100 & total_jobs <= 300 ~"#fb6a4a",
                                  total_jobs > 300 & total_jobs <= 600 ~"#cb181d",
                                  TRUE ~"#cccccc"),
               opacity = 1,
               label = ~paste0("Total jobs: ",total_jobs),
               group = "Home Locations of People Who Work Within Civic Center Block Groups") %>% 

  addPolygons(data = block_groups,
              fillOpacity = 0,
              weight = 1, color = "black", opacity = 1,
              label = ~paste0("GEOID: ", GEOID),
              group = "Block Groups") %>% 
  addPolygons(data = soi,
              fillOpacity = 0,
              weight = 3, color = "black", opacity = 1,
              group = "Sphere of Influence") %>% 
  
  hideGroup(c("Block Groups", "Sphere of Influence")) %>% 
  addLegend(position = "bottomleft",
            colors = c("#cb181d", "#fb6a4a", "#fcae91", "#fee5d9"),
            labels = c("301 to 600 jobs", "101 to 300 jobs", "51 to 100 jobs", "1 to 50 jobs"),
            title = "Number of Jobs",
            opacity = 1) %>%
  addLayersControl(
    baseGroups = c("Work Locations of People Who Live Within Civic Center Block Groups",
                   "Home Locations of People Who Work Within Civic Center Block Groups"),
    overlayGroups = c("Civic Center Block Groups","Sphere of Influence", "Block Groups"),
    options = layersControlOptions(collapsed=FALSE)
  )

  
```
```{r echo=FALSE, warning=FALSE, message=FALSE}
wac_summary <- read_rds("../../data/lihue-civiccentermobility/lehd_analysis/wac_2019_summary.rds")

fig <- plot_ly(wac_summary, labels = ~job_name, values = ~num_jobs, type = "pie")
fig <- fig %>% 
  layout(title = "Workplace Area Characteristics for Civic Center block groups",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig
```
```{r echo=FALSE, warning=FALSE, message=FALSE}
rac_summary <- read_rds("../../data/lihue-civiccentermobility/lehd_analysis/rac_2019_summary.rds")

fig <- plot_ly(rac_summary, labels = ~job_name, values = ~num_jobs, type = "pie")
fig <- fig %>% 
  layout(title = "Residence Area Characteristics for Civic Center block groups",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig
```



